### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by jakesmolka** [ethercis/EtherCISdocumentation#5]
Here:

https://github.com/ethercis/EtherCISdocumentation/blob/0287f1611853a216c988cbc5b48928bbe913b4f3/pages/etherCIS/APIs.md#L14

The link should be: https://code4health.org/platform/open_interfaces_apis/ehrscape/ehrscape_api_reference

**Comment by tony-shannon** [comment]
thanks @jakesmolka 
updated that now, if you'd like to retest.
Tony
